version: '3.8'

services:
  database:
    image: postgres:15
    container_name: database
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    depends_on:
      - database
    environment:
      DATABASE_URL: "postgresql://user:password@database:5432/app_db"
      PORT: 5000
    ports:
      - "5000:5000"
    volumes:
      - ./server:/server
    command: sh -c "npx prisma generate && npx prisma migrate dev --name init && npm run dev"

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: app
    depends_on:
      - server
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
    environment:
      - NODE_ENV=development
    command: npm start

volumes:
  pgdata:
